config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :genres
  resources :directors
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :genre
  has_many :movies

  validates :name, :nationality, :date_of_birth, :genre_id, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :directors
  has_many :movies

  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director
  belongs_to :genre

  validates :title, :release_year, :synopsis, :country_of_origin, :duration, :director_id, :genre_id, :image, presence: true

  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: %i[show edit update destroy]

  def index
    @directors = Director.order(:name)
  end

  def show
    @movies = @director.movies.order(:release_year)
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(director_params)

    if @director.save
      redirect_to directors_path, notice: 'Diretor cadastrado com sucesso!'
    else
      flash.now.notice = 'Não foi possível cadastrar diretor!'
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @director.update(director_params)
      redirect_to @director, notice: 'Diretor(a) atualizado com sucesso!'
    else
      flash.now.notice = 'Não foi possível atualizar diretor(a)!'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy

  end

  private

  def director_params
    params.require(:director).permit(:name, :nationality, :date_of_birth, :genre_id)
  end

  def set_director
    @director = Director.find(params[:id])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[show edit update destroy]

  def index
    @genres = Genre.order(:name)
  end

  def show

  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)

    if @genre.save
      redirect_to genres_path, notice: 'Gênero cadastrado com sucesso!'
    else
      flash.now.notice = 'Não possível cadastrar novo gênero!'
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @genre.update(genre_params)
      redirect_to @genre, notice: 'Gênero atualizado com sucesso!'
    else
      flash.now.notice = 'Não foi possível atualizar gênero!'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy

  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def set_genre
    @genre = Genre.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.order(:title)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[show edit update destroy]

  def show

  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to @movie, notice: 'Filme cadastrado com sucesso!'
    else
      flash.now.notice = 'Não foi possível cadastrar filme!'
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Filme atualizado com sucesso!'
    else
      flash.now.notice = 'Não foi possível atualizar filme!'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy

  end

  private

  def movie_params
    params.require(:movie).permit(:title, :release_year, :synopsis, :country_of_origin, :duration, :director_id, :genre_id, :image)
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/_form.html.erb
<div class='form-container'>
  <%= form_with model: @director do |f| %>
    <div>
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :nationality, 'Nacionalidade' %>
      <%= f.text_field :nationality %>
    </div>
    <div>
      <%= f.label :date_of_birth, 'Data de nascimento' %>
      <%= f.date_field :date_of_birth %>
    </div>
    <div>
      <%= f.label :genre_id, 'Gênero Favorito' %>
      <%= f.collection_select :genre_id, Genre.order(:name), :id, :name %>
    </div>
    <div>
      <%= f.submit 'Enviar' %>
    </div>
  <% end %>
</div>

app/views/directors/edit.html.erb
<h1>Editar <%= @director.name %></h1>

<%= render 'form' %>

app/views/directors/index.html.erb
<h1>Diretores</h1>

<div class='director-list'>
  <div class='new'><%= link_to 'Cadastrar novo diretor(a)', new_director_path %></div>

  <ul>
    <% @directors.each do |director| %>
      <li>
        <%= link_to director_path(director) do %>
          <%= director.name %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<% if @directors.empty? %>
  <p class='no-register'>Não há diretores cadastrados!</p>
<% end %>

app/views/directors/new.html.erb
<h1>Cadastrar Novo Diretor</h1>

<%= render 'form' %>

app/views/directors/show.html.erb
<h1><%= @director.name %></h1>

<div class='director'>
  <div class='director-info'>
    <p><strong>Nacionalidade:</strong> <%= @director.nationality %></p>
    <p><strong>Data de nascimento:</strong> <%= @director.date_of_birth %></p>
    <p><strong>Gênero favorito:</strong> <%= @director.genre.name %></p>
  
    <div class='edit'><%= link_to 'Editar', edit_director_path %></div>
  </div>
</div>

<div class='movie-list'>
  <h2>Filmes Dirigidos</h2>
  
  <ul>
    <% @movies.each do |movie| %>
      <li>
      <%= link_to movie_path(movie) do %>
        <%= movie.title %> (<%= movie.release_year %>)
        <div><%= image_tag movie.image, class:'img' %></div>
      <% end %>
      </li>
    <% end %>
  </ul>
</div>

<% if @director.movies.empty? %>
  <p class='no-register'>Não há filmes desse(a) diretor(a) cadastrados!</p>
<% end %>

app/views/genres/_form.html.erb
<div class='form-container'>
  <%= form_with model: @genre do |f| %>
    <div>
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.submit 'Enviar' %>
    </div>
  <% end %>
</div>

app/views/genres/edit.html.erb
<h1>Editar Gênero <%= @genre.name %></h1>

<%= render 'form' %>

app/views/genres/index.html.erb
<h1>Gêneros</h1>

<div class='genre-list'>
  <div class='new'><%= link_to 'Cadastrar novo gênero', new_genre_path %></div>
  
  <ul>
    <% @genres.each do |genre| %>
      <li>
        <%= link_to  genre_path(genre) do %>
          <%= genre.name %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<% if @genres.empty? %>
  <p class='no-register'>Não há gêneros cadastrados!</p>
<% end %>

app/views/genres/new.html.erb
<h1>Cadastrar Novo Gênero</h1>

<%= render 'form' %>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<div class='edit'><%= link_to 'Editar', edit_genre_path %></div>

<div class='movie-list'>
  <h2>Filmes do Gênero</h2>

  <ul>
    <% @genre.movies.each do |movie| %>
      <li>
      <%= link_to movie_path(movie) do %>
        <%= movie.title %> (<%= movie.release_year %>)
        <div><%= image_tag movie.image, class:'img' %></div>
      <% end %>
      </li>
    <% end %>
  </ul>
</div>

<% if @genre.movies.empty? %>
  <p class='no-register'>Não há filmes desse gênero cadastrados!</p>
<% end %>

app/views/home/index.html.erb
<h1>Filmes</h1>

<div class='movie-list'>
  <div class='new'><%= link_to 'Cadastrar novo filme', new_movie_path %></div>
  
  <ul>
    <% @movies.each do |movie| %>
      <li>
        <%= link_to movie_path(movie) do %>
          <%= movie.title %> (<%= movie.release_year %>)
          <div><%= image_tag movie.image, class:'img' %></div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<% if @movies.empty? %>
  <p class='no-register'>Não há filmes cadastrados!</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body> 
    <nav class='navbar'>
      <%= link_to root_path do %>
        <h1 class='header'>
          Movie<%= image_tag 'theaters', class: 'icon' %>App
        </h1>
      <% end %>

      <ul class='nav-items'>
        <li><%= link_to 'Gêneros', genres_path %></li>
        <li><%= link_to 'Diretores', directors_path %></li>
        <li><%= link_to 'Filmes', root_path %></li>
      </ul>      
    </nav>

    <main class='main'>
      <% if notice.present? %>
        <div class="<%= notice.include?('sucesso') ? 'success-message' : 'error-message' %>">
            <%= notice %>
        </div>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/movies/_form.html.erb
<div class='form-container'>
  <%= form_with model: @movie do |f| %>
    <div>
      <%= f.label :title, 'Título' %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :release_year, 'Ano de lançamento' %>
      <%= f.number_field :release_year %>
    </div>
    <div>
      <%= f.label :country_of_origin, 'País de origem' %>
      <%= f.text_field :country_of_origin %>
    </div>
    <div>
      <%= f.label :duration, 'Duração(min)' %>
      <%= f.number_field :duration, placeholder:'min', class: 'duration-field' %>
    </div>
    <div>
      <%= f.label :director_id, 'Direção' %>
      <%= f.collection_select :director_id, Director.order(:name), :id, :name %>
    </div>
    <div>
      <%= f.label :genre_id, 'Gênero' %>
      <%= f.collection_select :genre_id, Genre.order(:name), :id, :name %>
    </div>
    <div>
      <%= f.label :synopsis, 'Sinopse' %>
      <%= f.text_area :synopsis, class:'synopsis-field' %>
    </div>
    <div>
      <%= f.label :image, 'Imagem de pôster' %>
      <%= f.file_field  :image %>
    </div>
    <div>
      <%= f.submit 'Enviar' %>
    </div>
  <% end %>
</div>

app/views/movies/edit.html.erb
<h1>Editar <%= @movie.title %></h1>

<%= render 'form' %>

app/views/movies/new.html.erb
<h1>Cadastrar Novo Filme</h1>

<%= render 'form' %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<div class='movie'>
  <div class='img'>
    <%= image_tag @movie.image, class:'img' %>
  </div>
  <div class='movie-info'>
    <p><strong>Ano de lançamento:</strong> <%= @movie.release_year %></p>
    <p><strong>País de origem:</strong> <%= @movie.country_of_origin %></p>
    <p><strong>Duração:</strong> <%= @movie.duration %> min</p>
    <p><strong>Direção:</strong> <%= @movie.director.name %></p>
    <p><strong>Gênero:</strong> <%= @movie.genre.name %></p>
    <p><strong>Sinopse:</strong></p>
    <p class='synopsis'><%= @movie.synopsis %></p>
  </div>
</div>

<div class='edit'><%= link_to 'Editar', edit_movie_path %></div>